import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Bens",
      email: "benshamou@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Puma",
        logo: "/images/logo1.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "Mohamed",
      email: "exemple@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Zara Shirt",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 300,
      countInStock: 20,
      brand: "Zara",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Blue Shirt",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 320,
      countInStock: 2,
      brand: "Auchan",
      rating: 1,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas White Shirt",
      category: "Shirts",
      image: "/images/product-4.jpg",
      price: 160,
      countInStock: 0,
      brand: "Adidas",
      rating: 0.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Puma Short",
      category: "Shorts",
      image: "/images/product-5.jpg",
      price: 140,
      countInStock: 15,
      brand: "Puma",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Versace Short",
      category: "Shorts",
      image: "/images/product-6.jpg",
      price: 122,
      countInStock: 7,
      brand: "Versace",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
