const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:120,
            countInStock: 10,
            brand:'Nike',
            rating:3.5,
            numReviews:10,
            desciption:'high quality product',
        },
        {
            _id:'2',
            name:'Nike Slim Shirtt',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:300,
            countInStock: 20,
            brand:'Nike',
            rating:2,
            numReviews:10,
            desciption:'high quality product',
        },
        {
            _id:'3',
            name:'Nike Slim Shirttt',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:320,
            countInStock: 2,
            brand:'Nike',
            rating:1,
            numReviews:10,
            desciption:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Shirtttt',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:160,
            countInStock: 0,
            brand:'Nike',
            rating:0.5,
            numReviews:10,
            desciption:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Slim Shirttttt',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:140,
            countInStock: 15,
            brand:'Nike',
            rating:5,
            numReviews:10,
            desciption:'high quality product',
        },
        {
            _id:'6',
            name:'Nike Slim Shirtttttt',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:122,
            countInStock: 7,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            desciption:'high quality product',
        },
    ],
}
export default data;